# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataManager.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Manager(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1124, 829)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(440, 20, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.searchResult = QtWidgets.QTableWidget(Form)
        self.searchResult.setGeometry(QtCore.QRect(25, 81, 1071, 351))
        self.searchResult.setObjectName("searchResult")
        self.searchResult.setColumnCount(0)
        self.searchResult.setRowCount(0)
        self.searchResult.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 450, 511, 211))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(40)
        self.formLayout.setVerticalSpacing(28)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.Title = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Title)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.Author = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Author.setFont(font)
        self.Author.setObjectName("Author")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Author)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.Source = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Source.setFont(font)
        self.Source.setObjectName("Source")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Source)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(560, 450, 531, 211))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setHorizontalSpacing(40)
        self.formLayout_2.setVerticalSpacing(28)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.Date = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Date.setFont(font)
        self.Date.setObjectName("Date")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Date)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.Use = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Use.setFont(font)
        self.Use.setObjectName("Use")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Use)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.Download = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Download.setFont(font)
        self.Download.setObjectName("Download")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Download)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 680, 1061, 111))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(32)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Search = QtWidgets.QPushButton(self.widget)
        self.Search.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Search.setFont(font)
        self.Search.setObjectName("Search")
        self.horizontalLayout.addWidget(self.Search)
        self.Add = QtWidgets.QPushButton(self.widget)
        self.Add.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Add.setFont(font)
        self.Add.setObjectName("Add")
        self.horizontalLayout.addWidget(self.Add)
        self.Delete = QtWidgets.QPushButton(self.widget)
        self.Delete.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Delete.setFont(font)
        self.Delete.setObjectName("Delete")
        self.horizontalLayout.addWidget(self.Delete)
        self.revise = QtWidgets.QPushButton(self.widget)
        self.revise.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.revise.setFont(font)
        self.revise.setObjectName("revise")
        self.horizontalLayout.addWidget(self.revise)
        self.label_2.setBuddy(self.Title)
        self.label_3.setBuddy(self.Author)
        self.label_4.setBuddy(self.Source)
        self.label_5.setBuddy(self.Title)
        self.label_6.setBuddy(self.Author)
        self.label_7.setBuddy(self.Source)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "管理数据"))
        self.label_2.setText(_translate("Form", "标题"))
        self.label_3.setText(_translate("Form", "作者"))
        self.label_4.setText(_translate("Form", "来源"))
        self.label_5.setText(_translate("Form", "日期"))
        self.label_6.setText(_translate("Form", "被引数"))
        self.label_7.setText(_translate("Form", "下载数"))
        self.Search.setText(_translate("Form", "查询"))
        self.Add.setText(_translate("Form", "增加"))
        self.Delete.setText(_translate("Form", "删除"))
        self.revise.setText(_translate("Form", "全览"))

